export const FONT_PROBE = [
  "Minion Pro",
  "Myriad Pro",
  "Adobe Garamond Pro",
  "Source Code Pro",
  "Source Sans 3",
  "Calibri",
  "Cambria",
  "Consolas",
  "Segoe UI",
  "Wingdings",
  "Candara",
  "SF Mono",
  "SF Pro Display",
  "New York",
  "Fira Code",
  "JetBrains Mono",
  "Cascadia Code",
  "Hack",
  "Iosevka",
  "Operator Mono",
  "Inconsolata",
  "Ubuntu Mono",
  "Menlo",
  "Andale Mono",
  "PT Sans",
  "Lucida Console",
  "American Typewriter",
  "Avenir Next",
  "DIN Alternate",
  "Futura",
] as const;
